version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - published: ${APP_PORT:-8888}
        target: 8888
    volumes:
      - .:/app/
    environment:
      JWT_SECRET: ${JWT_SECRET}
